version: '3'

services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8888:8888"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: mongo
    expose:
      - "27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: